# VARIABLE VSCODE
#@baseUrl = http://localhost:3333

< {%
	// client.global.set("my_cookie", response.headers.valuesOf("Set-Cookie")[0]);
	client.global.set('baseUrl', 'http://localhost:3333');
	client.global.set('accessToken', '');
%}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
	"name": "Diego Fernandes",
	"email": "diego@rocketseat.com.br",
	"password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
	"name": "X",
	"email": "diego@rocketseat.com.br",
	"password": "123456"
}
> {%
	client.global.set('accessToken', response.body.accessToken)
%}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
}
